### ISSUE TITLE
UnknownHostException: presto

### ISSUE THREAD

**Issue by benyaa** [wix-incubator/quix#13]
Hi,
I've tried installing quix on my server.. However, When I try to run a query, the backend throws the following exception:

> [quix-db-tree-32] quix.presto.SingleResultBuilder          : Got exception
backend_1   |
backend_1   | java.net.UnknownHostException: presto
backend_1   |   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[na:na]
backend_1   |   at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
backend_1   |   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
backend_1   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[na:na]
backend_1   |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[na:na]
backend_1   |   at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:na]
backend_1   |   at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[na:na]
backend_1   |   at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1242) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1009) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[na:na]
backend_1   |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
backend_1   |   at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
backend_1   |   at scalaj.http.HttpRequest.doConnection(Http.scala:367) ~[scalaj-http_2.12-2.4.1.jar:2.4.1]
backend_1   |   at scalaj.http.HttpRequest.exec(Http.scala:343) ~[scalaj-http_2.12-2.4.1.jar:2.4.1]
backend_1   |   at scalaj.http.HttpRequest.asString(Http.scala:491) ~[scalaj-http_2.12-2.4.1.jar:2.4.1]
backend_1   |   at quix.presto.rest.ScalaJPrestoStateClient.$anonfun$init$3(ScalaJPrestoStateClient.scala:22) ~[quix-presto-module-1.0.0-SNAPSHOT.jar:na]
backend_1   |   at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:81) ~[monix-eval_2.12-3.0.0-RC2.jar:3.0.0-RC2]
backend_1   |   at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:108) ~[monix-eval_2.12-3.0.0-RC2.jar:3.0.0-RC2]
backend_1   |   at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74) ~[monix-eval_2.12-3.0.0-RC2.jar:3.0.0-RC2]
backend_1   |   at monix.eval.internal.TaskSleep$SleepRunnable.run(TaskSleep.scala:62) ~[monix-eval_2.12-3.0.0-RC2.jar:3.0.0-RC2]
backend_1   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
backend_1   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
backend_1   |   at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

This is my backend application.properties file:
>server.port=8080
presto.api=test-server01:8090
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

Am I missing something?

**Comment by AlexeySoshin** [comment]
Thanks for reporting!
This should be fixed by PR #10 
You will be able to configure your Presto in `.env` file like this:
PRESTO_API=`http://test-server01:8090/v1`
