### ISSUE TITLE
Mandatory authentication?

### ISSUE THREAD

**Issue by benyaa** [wix-incubator/quix#16]
Hi,
Could authentication method be required? 
I've tried to run quix with basic configuration and got the following exception in backend when trying to run a query:

> backend_1   | quix.api.users.RequestNotAuthenticated: Request not authenticated
backend_1   |   at quix.web.auth.JwtUsers.$anonfun$auth$5(JwtUsers.scala:20) ~[classes/:na]
backend_1   |   at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.12.7.jar:na]
backend_1   |   at quix.web.auth.JwtUsers.auth(JwtUsers.scala:20) ~[classes/:na]
backend_1   |   at quix.web.controllers.PrestoController.handleTextMessage(PrestoController.scala:23) ~[classes/:na]
backend_1   |   at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.1.2.RELEASE.jar:5.1.2.RELEASE]
backend_1   |   at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.1.2.RELEASE.jar:5.1.2.RELEASE]
backend_1   |   at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.1.2.RELEASE.jar:5.1.2.RELEASE]
backend_1   |   at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.1.2.RELEASE.jar:5.1.2.RELEASE]
backend_1   |   at org.springframework.web.socket.adapter.jetty.JettyWebSocketHandlerAdapter.onWebSocketText(JettyWebSocketHandlerAdapter.java:83) ~[spring-websocket-5.1.2.RELEASE.jar:5.1.2.RELEASE]
backend_1   |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
backend_1   |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
backend_1   |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
backend_1   |   at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
backend_1   |   at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:71) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:234) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:226) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:476) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:183) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:219) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:244) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:560) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:391) ~[websocket-common-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) ~[jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) ~[jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
backend_1   |   at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
backend_1   |

Also, When I try to view a table's details in the DB explorer, I get the following error in console:

> Error: "[$resource:badcfg] Error in resource configuration for action `query`. Expected response to contain an array but got an object (Request: GET /api/db/explore/cassandra/keyspace1/table_test1)
https://errors.angularjs.org/1.7.8/$resource/badcfg?p0=query&p1=array&p2=object&p3=GET&p4=%2Fapi%2Fdb%2Fexplore%2Fcassandra%2Fkeyspace1%2Ftable_test1"
    i http://test-server01:3000/app.bundle.min.js:1
    G http://test-server01:3000/app.bundle.min.js:1
    u http://test-server01:3000/app.bundle.min.js:1
    u http://test-server01:3000/app.bundle.min.js:1
    $digest http://test-server01:3000/app.bundle.min.js:1
    $apply http://test-server01:3000/app.bundle.min.js:1
    b http://test-server01:3000/app.bundle.min.js:1
    y http://test-server01:3000/app.bundle.min.js:1
    onload http://test-server01:3000/app.bundle.min.js:1
 Possibly unhandled rejection: {}

It  seems that the response is okay(and yes, an object), but not an array.

**Comment by frolovv** [comment]
@benyaa tnx for reporting it!

this commit should fix it : https://github.com/wix-incubator/quix/commit/70509404726ab88b3b79264e8dd3ce7424503ea3

please pull latest updates and rebuild via `git pull && docker-compose build`

**Comment by benyaa** [comment]
> 
> 
> @benyaa tnx for reporting it!
> 
> this commit should fix it : [7050940](https://github.com/wix-incubator/quix/commit/70509404726ab88b3b79264e8dd3ce7424503ea3)
> 
> please pull latest updates and rebuild via `git pull && docker-compose build`

Also, check the second part about the table object parsing

**Comment by frolovv** [comment]
@antonpod will look into the DB explorer issue.

also, the auth is still failing i'm on it

**Comment by frolovv** [comment]
auth should fallback to dummy user now : 

![image](https://user-images.githubusercontent.com/2934915/56275060-a78a4480-6108-11e9-9ff0-7199bfea21b1.png)

**Comment by antonpod** [comment]
DB explorer error fixed:
https://github.com/wix-incubator/quix/commit/479605490156b62f8c6fee15c4d6dfdd2ff6c8a5

**Comment by frolovv** [comment]
closing, both issues are fixed 

![image](https://user-images.githubusercontent.com/2934915/56280365-b83fb800-6112-11e9-9502-f14ebe1bb979.png)
