### ISSUE TITLE
After some time I get a message "Connection Lost"

### ISSUE THREAD

**Issue by richiesgr** [wix-incubator/quix#46]
Hi
After a night the process up and running when I try to make a query I get a message "connection lost" 
Seems to be a problem with timeout of connections or something like that 
I've tried to see for exception in the log container but nothing there
Tried to restart the container do not work either !?!
I join a screenshot

![Screenshot from 2019-04-24 13-50-52](https://user-images.githubusercontent.com/163108/56654183-24349a00-6698-11e9-913a-8e69333f85d5.png)

**Comment by frolovv** [comment]
@richiesgr 

i see that you are deploying on ec2

make sure that your `.env` file contains 
`BACKEND_PUBLIC_URL=<public ip of the ec2 machine>:8081`

please update the `.env` and run `docker-compose down && docker-compose up -d`

**Comment by richiesgr** [comment]
Hi
After git pull last version and add BACKEND_PUBLIC_URL to .env the frontend don't start anymore
I get this

[Nest] 17   - 04/28/2019, 8:37 AM   [NestFactory] Starting Nest application...
****** Current Enviorment: DEV ******
[Nest] 17   - 04/28/2019, 8:37 AM   [InstanceLoader] TypeOrmModule dependencies initialized +31ms
[Nest] 17   - 04/28/2019, 8:37 AM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 17   - 04/28/2019, 8:37 AM   [ExceptionHandler] Nest can't resolve dependencies of the FileTreePlugin (function Connection(options) {
        /**
         * Indicates if connection is initialized or not.
         */
        this.isConnected = false;
        /**
         * Migration instances that are registered for this connection.
         */
        this.migrations = [];
        /**
         * Entity subscriber instances that are registered for this connection.
         */
        this.subscribers = [];
        /**
         * All entity metadatas that are registered for this connection.
         */
        this.entityMetadatas = [];
        this.name = options.name || "default";
        this.options = options;
        this.logger = new LoggerFactory_1.LoggerFactory().create(this.options.logger, this.options.logging);
        this.driver = new DriverFactory_1.DriverFactory().create(this);
        this.manager = this.createEntityManager();
        this.namingStrategy = options.namingStrategy || new DefaultNamingStrategy_1.DefaultNamingStrategy();
        this.queryResultCache = options.cache ? new QueryResultCacheFactory_1.QueryResultCacheFactory(this).create() : undefined;
        this.relationLoader = new RelationLoader_1.RelationLoader(this);
        this.relationIdLoader = new RelationIdLoader_1.RelationIdLoader(this);
    }_DbFolderRepository, ?). Please make sure that the argument at index [1] is available in the EventSourcingModule context. +25ms
Error: Nest can't resolve dependencies of the FileTreePlugin (function Connection(options) {
        /**
         * Indicates if connection is initialized or not.
         */
        this.isConnected = false;
        /**
         * Migration instances that are registered for this connection.
         */
        this.migrations = [];
        /**
         * Entity subscriber instances that are registered for this connection.
         */
        this.subscribers = [];
        /**
         * All entity metadatas that are registered for this connection.
         */
        this.entityMetadatas = [];
        this.name = options.name || "default";
        this.options = options;
        this.logger = new LoggerFactory_1.LoggerFactory().create(this.options.logger, this.options.logging);
        this.driver = new DriverFactory_1.DriverFactory().create(this);
        this.manager = this.createEntityManager();
        this.namingStrategy = options.namingStrategy || new DefaultNamingStrategy_1.DefaultNamingStrategy();
        this.queryResultCache = options.cache ? new QueryResultCacheFactory_1.QueryResultCacheFactory(this).create() : undefined;
        this.relationLoader = new RelationLoader_1.RelationLoader(this);
        this.relationIdLoader = new RelationIdLoader_1.RelationIdLoader(this);
    }_DbFolderRepository, ?). Please make sure that the argument at index [1] is available in the EventSourcingModule context.
    at Injector.lookupComponentInExports (/service/node_modules/@nestjs/core/injector/injector.js:180:19)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at Object.<anonymous> (/service/node_modules/ts-node/src/bin.ts:157:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
 1: 0x95b8f0 node::Abort() [node]
 2: 0x9c75f9  [node]
 3: 0xbc4eda  [node]
 4: 0xbc5a89 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 5: 0x2b65b77cfc5d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! quix-node-backend@0.0.1 start: `ts-node --files -r tsconfig-paths/register build-scripts/start.ts`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the quix-node-backend@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-28T08_37_28_942Z-debug.log

any idea ?

**Comment by antonpod** [comment]
@richiesgr please see if rebuilding `docker-compose build`) solves it

**Comment by richiesgr** [comment]
@antonpod No it's not same error

**Comment by sthuck** [comment]
@richiesgr 
I'm on it, will update

**Comment by sthuck** [comment]
@richiesgr 
the nestjs issues is fixed, please rebuild the docker image. Sorry for sudden breakage and thanks for helping 👍 
let us know if it works

**Comment by richiesgr** [comment]
Hi
it's ok now the frontend run
however I'm not going to close this ticket now because I've not checked yet the first issue.
Thanks for your quick help

**Comment by antonpod** [comment]
@richiesgr 
Closing for now. Please update if you're still experience issues.
