### ISSUE TITLE
How to use my presto cluster ?

### ISSUE THREAD

**Issue by richiesgr** [wix-incubator/quix#9]
I've succeed to access my presto cluster 
I see quix making queries to this cluster now 
but nothing ! the loading db keep busy and no schema is retrieved from the server
The only request made repeatedly is

`select 1 from raptor.audience.monthly_users limit 1 `

The table name is monthly_users
Is there something that must be configured ?
Thanks

**Comment by frolovv** [comment]
@richiesgr we are on it. 

hopefully this PR https://github.com/wix-incubator/quix/pull/10/files
will fix it and we will update the documentation with an example of passing external config to docker compose

cc @sthuck @AlexeySoshin

**Comment by AlexeySoshin** [comment]
@richiesgr the relevant fix was merged. Feel free to test it, and let us know if that solved your issue :)

**Comment by richiesgr** [comment]
Working as Expected 
Thanks
